### ISSUE TITLE
Dashboard not showing data

### ISSUE THREAD

**Issue by Ivan-Marquez** [mihailescu2m/powerwall_monitor#10]
Hello @mihailescu2m,

I was able to run the docker scripts successfully. However, when I go to the dashboard, it doesn't display any data:

![alt text](http://g.recordit.co/e4OxkeAylz.gif "Dashboard")

Inside the docker-compose logs, I see the following errors:

```bash
telegraf    | 2020-05-19T18:25:58Z E! [inputs.http] Error in plugin: [url=https://powerwall/api/meters/aggregates]: Get https://powerwall/api/meters/aggregates: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
telegraf    | 2020-05-19T18:25:58Z E! [inputs.http] Error in plugin: [url=https://powerwall/api/system_status/soe]: Get https://powerwall/api/system_status/soe: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

Any suggestions on how to fix this? Thanks!

**Comment by jackkorber** [comment]
Did you change the the address to the powerwall ip?
https://powerwall-ip/api/system_status/soe


I saw that you are from Puerto Rico. 

https://www.facebook.com/groups/2599787213588089/?ref=share

**Comment by mihailescu2m** [comment]
Looks like it cannot connect to the Powerwall. Did you use the correct IP address?

**Comment by Ivan-Marquez** [comment]
Thanks for your reply guys!

I'm able to retrieve data from `https://<powerwall-ip>/api/system_status/soe` and `https://<powerwall-ip>/api/meters/aggregates`. Also, I'm assigning the correct IP Address inside `powerwall.yml`. Apparently, the container is not able to connect to that IP. Am I missing some sort of binding in the docker-compose file? Thanks!

**Comment by mihailescu2m** [comment]
"extra_hosts" in powerwall.yml should be the only thing you need to have set up correctly.
otherwise, router configuration or firewall on host to allow connections.
