### ISSUE TITLE
Failed to update datasource

### ISSUE THREAD

**Issue by nswfugitive** [mihailescu2m/powerwall_monitor#2]
Hi - and sorry to be a pain.  When updating the data source for the powerwall DB I get the error shown in the title.

**Comment by mihailescu2m** [comment]
try:

1. `docker -f powerwall.yml down`
2. remove all files in grafana and influxdb (will delete the database too)
3. `docker -f powerwall.html up -d`

See if that works

**Comment by nswfugitive** [comment]
Getting the following:

docker -f powerwall.yml down
unknown shorthand flag: 'f' in -f

**Comment by mihailescu2m** [comment]
`docker-compose` sorry, updated above.

**Comment by nswfugitive** [comment]
That did it - but I not sure on the next step - where is the "Sun and Moon" supposed to point to?

**Comment by mihailescu2m** [comment]
You can try to skip that step

**Comment by nswfugitive** [comment]
Yep, I did.  Everything seems to be working except the Live Monitoring Graph of Energy Usage says No data in the middle of the graph.  The current state and six measurement are updating.

**Comment by mihailescu2m** [comment]
try deleting this from `dashboard.json`:
```
{
          "datasource": "Sun and Moon",
          "refId": "F",
          "target": "sun_altitude"
}
```
OR: from dashboard settings (top right row of icons), make the dashboard editable, then save dashboard (also top right row of icons). Next, click on the chart title, select EDIT, scroll down at the last entry down (with the Sun and Moon) and delete it.

OR:  from Configuration/Data Sources (left row of icons), select ADD DATASOURCES and select Sun And Moon and enter your lat and long:

![Capture](https://user-images.githubusercontent.com/4421731/71227416-0a367e80-232f-11ea-9c89-c6aa1ddfcd08.JPG)

**Comment by nswfugitive** [comment]
All working now - thanks heaps for your help.  And enjoy the beers I sent you...  :-)
