### ISSUE TITLE
scaling of the graph

### ISSUE THREAD

**Issue by nswfugitive** [mihailescu2m/powerwall_monitor#3]
I noticed that the scale on the graph only goes up to ~5kW+, and doesn't seem to change the scale.  It just flatlines although the data when you hover over the graph is correct (ex. 6.81kW).

**Comment by mihailescu2m** [comment]
from dashboard settings (top right row), select make editable, then save dashboard (also top right row).
then click on chart title, then edit, from left row select Visualisation, and enter whatever range you wish (or let it empty for autoscale).

<img width="1025" alt="Screen Shot 2019-12-21 at 1 30 13 pm" src="https://user-images.githubusercontent.com/4421731/71302000-1cc7bb00-23f6-11ea-9b67-6dafa9a8cc99.png">

**Comment by nswfugitive** [comment]
Thanks mate - sorry to be a pain.  Don't know grafana but I'll learn.  Your patience is appreciated.
