### ISSUE TITLE
Time of Use for Savings Graph

### ISSUE THREAD

**Issue by nitro182** [mihailescu2m/powerwall_monitor#5]
Hey,

Thanks so much for your work on this project I liked it so much that I donated :)

One area I am struggling is to see if I could some how build in time of use into the savings graph.

In summary, my peak hours are Mon-Fri 2pm-8pm, shoulder is Mon-Fri 7am to 2pm and 8pm to 10pm, Off peak is Mon-Fri 10pm to 7am.

Weekends/Public Holidays are Off Peak 10pm to 7am, Shoulder 7am to 10pm.

Also, I made a change to the battery savings calculations:

SELECT f - t FROM (SELECT sum(from_pw)  * 0.358 AS f, sum(to_pw) * 0.21 AS t FROM kwh.http WHERE  $timeFilter tz('Australia/Sydney'))

This should takes into account lost FIT because this could have been exported and caters for any loss in charging.

Cheers,
Adam.

**Comment by mihailescu2m** [comment]
Hi Adam,

Unfortunately InfluxDB is pretty bad at doing standard SQL operations (e.g. there's no join, no compounding operations, etc), so it's extremely difficult to do time-of-use.
You can have a read e.g. here: https://stackoverflow.com/questions/42819058/query-influxdb-for-specific-hours-every-day to see how to get hours of day, but as you can see it's pretty difficult. You can also try to build different retention policies for different time of day periods, then aggregate those, but it's also quite complicated.

**Comment by nitro182** [comment]
Yeah, I spent about 3 hours yesterday researching InfluxDB and sort of came to the same solution but I thought I'd check with you as I'm not as familiar with it compared to standard SQL.

Thanks for confirming though!
