### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by jackkorber** [mihailescu2m/powerwall_monitor#7]
Is posible add the data from https://powerwall/api/system_status/grid_status to the database? Could you point me in the correct path?

**Comment by mihailescu2m** [comment]
Yes, add the URL to telegraf.conf (around line 105)

**Comment by jackkorber** [comment]
That was my initial approach and does not see it in the data.  I closed anything and open and don’t see the data. Do any to perform another action?

**Comment by mihailescu2m** [comment]
Did you add the data to Grafana in a new panel?

**Comment by jackkorber** [comment]
I tried to add new query. To get it. 


I don’t know if if s the correct way.

**Comment by jackkorber** [comment]
Do you have any suggestions?

**Comment by mihailescu2m** [comment]
I tried adding the URL, and it worked for me.
Add the URL to telegraf, and rebuild the image (eg try `docker-compose -f powerwall.yml down` then `docker-compose -f powerwall.yml up --build telegraf`)
