### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by AmateurCritic** [mihailescu2m/powerwall_monitor#8]
Thank you for this potentially very useful display.

I'm using a RPi 3B+, running Linux 9, (stretch).

I followed the installion guide in readme.md.

I had problems from "docker exec -it influxdb influx" and had to pull docker from https://get.docker.com/

pi@GDU-ESP-6912:~/Powerwall_Monitor $ docker exec -it influxdb influx
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/influxdb/json: dial unix /var/run/docker.sock: connect: permission denied

pi@GDU-ESP-6912:~/Powerwall_Monitor $ sudo docker-compose up
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see Compose file version 3 reference

I copied powerwall.yml to the default docker-compose.yml and ran again....

pi@GDU-ESP-6912:~/Powerwall_Monitor $ sudo docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.influxdb.volumes contains an invalid type, it should be a string
services.telegraf.volumes contains an invalid type, it should be a string
services.grafana.volumes contains an invalid type, it should be a string
services.influxdb.volumes contains an invalid type, it should be a string
services.influxdb.ports is invalid: Invalid port "{'target': 8086, 'mode': 'host', 'published': 8086}", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.influxdb.ports contains an invalid type, it should be a string, or a number
services.grafana.ports is invalid: Invalid port "{'target': 9000, 'mode': 'host', 'published': 9000}", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.grafana.ports contains an invalid type, it should be a string, or a number

I've checked on the git supository and the source was updated on the 16th. Dec 2019, so it should be current.

I can't get the database running so I'm stalled.

**Comment by mihailescu2m** [comment]
What docker version do you have installed?

```
~$ docker --version
Docker version 19.03.5, build 633a0ea
```
