### ISSUE TITLE
Some Charts random data

### ISSUE THREAD

**Issue by nappyshock** [mihailescu2m/powerwall_monitor#9]
Hi, I'm trying to get your monitoring setup on a Raspberry pi, i'm new to this so am limited in troubleshooting.
I've nearly got it working. I can bringup the Grafana web page and the live monitoring is all looking good and updating correctly in 5min increments.
However all the other charts seem to give random data, if i set the refresh in the top right of the page to a value ie 30sec all the charts (except live monitoring) come back with what seems like  random value at each refresh, ie the battery will show 11%, then at refresh 70%, then 61% etc, all the charts are like this including monthly data.
Would you have any ideas where this might be going wrong?

**Comment by nappyshock** [comment]
Just to clarify, when i  say the live monitoring chart is ok i mean the energy usage graph.
It's all the others.... powerwall, savings, current state, home usage, from powerwall, from grid etc that are returning random incorrect data.

**Comment by nappyshock** [comment]
I suspect my databases are not being populated, this is my first attempt at getting something working from github so my install method may have been wrong, to give you clues, how i did it....
Created a folder on the Pi download your files to it and extracted them in that folder, amended the files as per your instructions and then from the pi Linux cli, changed to the powerwall_monitor-master folder and ran all your commands from there.

Here is an image of my folder structure...

![image](https://user-images.githubusercontent.com/51824227/79685100-f6901b80-822d-11ea-8c45-aa58f40b43f2.png)

**Comment by nappyshock** [comment]
With my limited knowledge i suspect it may be a permission issue, i've played about changing ownership of the /var/lib/grafana and /var/lib/docker folders on the pi to no avail. 
The energy usage graph is working perfectly but when you look at all the other values on the grafana web page with the edit function, the query is set to default for some reason.
![image](https://user-images.githubusercontent.com/51824227/79833697-bce12100-83a3-11ea-8ed4-bfac2882ad0f.png)

**Comment by nappyshock** [comment]
I've found a workaround (but not the reason for the issue), for each of the Panels that have their Queries set to default, in the panel json settings the datasource is set to null, i've amended them to influxDB.......

![image](https://user-images.githubusercontent.com/51824227/79875376-7c07fd00-83e1-11ea-9698-1911061a2627.png)

![image](https://user-images.githubusercontent.com/51824227/79875418-8a561900-83e1-11ea-9b5b-d7bb49b63dfa.png)

The dashboard is now all working perfectly, excellent software... Thanks.

![image](https://user-images.githubusercontent.com/51824227/79875722-f20c6400-83e1-11ea-8a96-e3f7798176d1.png)

**Comment by mihailescu2m** [comment]
This was a hard one to find, glad you figured it out.
I think you have to set influxdb as "default' in the database section initially when you add the source, and that would've fixed it...
I'll try to find time to have the chart and database provisioned directly into grafana, so you don't have to add it manually - but time is very hard to find with the kids at home now...

On a side note, nice solar curve you got there :)
Since you have an idea now how Grafana works, you have the skills to edit the Savings chart and update it with your own FIT values ;)
